### ISSUE TITLE
GCS test failures for 'headers'

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-resumable-media-python#41]
https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/3858

```python
______________________ Test_Blob.test__do_download_simple ______________________
Traceback (most recent call last):
  File "/var/code/gcp/storage/tests/unit/test_blob.py", line 504, in test__do_download_simple
    blob._do_download(transport, file_obj, download_url, headers)
  File "/var/code/gcp/storage/google/cloud/storage/blob.py", line 448, in _do_download
    download.consume(transport)
  File "/var/code/gcp/.nox/unit-2-7/lib/python2.7/site-packages/google/resumable_media/requests/download.py", line 174, in consume
    self._write_to_stream(result)
  File "/var/code/gcp/.nox/unit-2-7/lib/python2.7/site-packages/google/resumable_media/requests/download.py", line 120, in _write_to_stream
    local_hash = _add_decoder(response.raw, md5_hash)
  File "/var/code/gcp/.nox/unit-2-7/lib/python2.7/site-packages/google/resumable_media/requests/download.py", line 315, in _add_decoder
    encoding = response_raw.headers.get(u'content-encoding', u'').lower()
AttributeError: '_io.BytesIO' object has no attribute 'headers'
```

**Comment by dhermes** [comment]
I'm on it. `0.3.1` just means the mock needs to grow some more feathers.

**Comment by dhermes** [comment]
@tseaver Just realized you filed this against `google-resumable-media-python`.

The "bug" is simply that the mocks (on the `google-cloud-storage` side) are no longer valid.

I'm fixing it either way.

**Comment by tseaver** [comment]
Are there any other functional (non-mocked unit) tests for `google-resumable-media`, beside those in `google-cloud-storage`?  I'm really puzzled that the stream object itself is supposed to have headers.

**Comment by dhermes** [comment]
@tseaver The `stream` (which is an `io.BytesIO`) is a "good-enough" approximation of a `urllib3.response.HTTPResponse` (i.e. we were previously only using `read()` and `close()` on `response.raw`)

**Comment by dhermes** [comment]
There are plenty of system tests in `tests/system`. One of them is currently broken because of spec adherence issues with `gzip`-encoded data. (i.e. this library didn't account for the behavior to change)
